### ISSUE TITLE
Netloader fails to boot 3dsx

### ISSUE THREAD

**Issue by endrift** [smealum/3ds_hb_menu#45] opened 2016-02-13 03:00 UTC
As of dc6a438acd62530c5669911f61527d67064e30e7, netloader will hang on the *hax 2.5 debug screen, with the bottom screen blue. It works fine in the previous commit. I'm using menuhax on 9.2 (n3DS) as the entry point.

**Comment by WinterMute** [comment] 2016-02-13 13:51
Can you try this one?
[boot.zip](https://github.com/smealum/3ds_hb_menu/files/129157/boot.zip)

**Comment by endrift** [comment] 2016-02-13 18:45
Same problem.

**Comment by yellows8** [comment] 2016-02-13 19:32
Are you using an unmodified *hax payload with menuhax?(If not, try restoring it)

**Comment by endrift** [comment] 2016-02-13 19:32
I'm using whatever the manager downloaded. I've got it slightly configured, but it should be the same payload.

**Comment by yellows8** [comment] 2016-02-13 19:34
By "configured" you only mean options in menuhax_manager, nothing from manually modifying the ropbin on SD right?

**Comment by endrift** [comment] 2016-02-13 19:35
Correct. Deleting the config didn't change anything.

**Comment by yellows8** [comment] 2016-02-13 19:38
What's the last line displayed on the top-screen?

**Comment by endrift** [comment] 2016-02-13 19:41
Using browserhax_fright as the entry point yields no difference.

Last two lines (for both) are
    got handle : hb:ndsp
    002d800e

Holding L+R+B+Down yields a magenta screen and eventually crashes into the home menu.

**Comment by endrift** [comment] 2016-02-14 05:47
The blue screen hang happens every single time (I've tried 10+, possibly as many as 30). Based on a conversation with @WinterMute in IRC, I tried specifying -0 to be the path to the executable, which caused the hang to go away and it to actually launch.

**Comment by fincs** [comment] 2016-02-21 23:35
I submitted a fix for this issue in hax 2.5.

**Comment by fincs** [comment] 2016-02-24 14:17
This should be fixed in hax 2.6.

**Closed by fincs** 2016-02-24 14:17 UTC

**Comment by endrift** [comment] 2016-02-25 06:40
Seems to still be broken in hax 2.6.

**Comment by smealum** [comment] 2016-02-25 06:58
WOW did fincs make me publish a fix without testing it first ? smh

**Comment by endrift** [comment] 2016-02-25 06:59
idk, I'm just using the --arg0 workaround for now since that works fine on my end.

**Comment by suloku** [comment] 2016-02-25 07:45
I used netloader yesterday and had no problems?
May it be because I was using my hbl mod? But netloading vode should be the same. I have no problems in either 9.2 or 10.6.

You may try this boot.3dsx: https://github.com/suloku/3ds_hb_menu/blob/patch-1/_release/boot.3dsx

**Comment by fincs** [comment] 2016-02-25 10:26
I tested the netloader, making sure to trigger the bug condition before sending the PR; and not only did I reproduce the bug, but I also verified that the modifications I did fixed the bug.

**Comment by smealum** [comment] 2016-02-25 18:24
wow so did endrift LIE ? smh

**Comment by endrift** [comment] 2016-02-25 18:51
The only additional detail beyond what I said earlier (menuhax entry point on 9.2 using *hax 2.6 payload) is that I'm using current master on hbl. I guess I can try updating 3dslink but there might not be any updates since I last built it.

**Comment by suloku** [comment] 2016-02-25 19:01
Maybe problem lies within your custom built 3dslink?

**Comment by endrift** [comment] 2016-02-25 21:07
Hm, could be. I was trying to debug it, but maybe I left it in a weird state. Will check tonight.

**Comment by endrift** [comment] 2016-02-29 08:05
Reverting my netloader changes didn't change things at all.

**Comment by smealum** [comment] 2016-03-04 03:13
oh hey this is funny turns out my git pull from before 10.6 payload release
failed so 2.6 doesnt include fincs's changes !

i still blame fincs but yeah i guess this issue isnt yet fixed in real
release.
